"""create_menu_management_tables

Revision ID: 50821e3e34c9
Revises: 
Create Date: 2026-01-10 12:38:51.482043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect, text

# revision identifiers, used by Alembic.
revision: str = '50821e3e34c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Get connection and inspector to check for existing tables
    connection = op.get_bind()
    inspector = inspect(connection)
    existing_tables = inspector.get_table_names()
    
    # ### commands auto generated by Alembic - please adjust! ###
    # Create master_table_list if it doesn't exist
    if 'master_table_list' not in existing_tables:
        op.create_table('master_table_list',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('table_name', sa.String(length=255), nullable=False),
            sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('created_by', sa.String(length=255), nullable=True),
            sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_by', sa.String(length=255), nullable=True),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('table_name')
        )
        # Create index only if table was just created
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('master_table_list')]
        if 'ix_master_table_list_id' not in existing_indexes:
            op.create_index(op.f('ix_master_table_list_id'), 'master_table_list', ['id'], unique=False)
    
    # Create perdix_mp_fee_configurations if it doesn't exist
    if 'perdix_mp_fee_configurations' not in existing_tables:
        op.create_table('perdix_mp_fee_configurations',
            sa.Column('id', sa.BigInteger(), nullable=False),
            sa.Column('organization_type', sa.String(length=255), nullable=False),
            sa.Column('organization_id', sa.String(length=255), nullable=False),
            sa.Column('subscription_fee_annual', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
            sa.Column('subscription_fee_currency', sa.String(length=10), server_default='INR', nullable=False),
            sa.Column('is_subscription_applicable', sa.Boolean(), server_default='false', nullable=False),
            sa.Column('subscription_period_months', sa.Integer(), server_default='12', nullable=False),
            sa.Column('listing_fee_percentage', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
            sa.Column('listing_fee_fixed', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
            sa.Column('is_listing_fee_applicable', sa.Boolean(), server_default='false', nullable=False),
            sa.Column('is_listing_fee_payable_on_posting', sa.Boolean(), server_default='false', nullable=False),
            sa.Column('commitment_fee_percentage', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
            sa.Column('commitment_fee_fixed', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
            sa.Column('is_commitment_fee_applicable', sa.Boolean(), server_default='false', nullable=False),
            sa.Column('success_fee_percentage', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
            sa.Column('success_fee_fixed', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
            sa.Column('is_success_fee_applicable', sa.Boolean(), server_default='false', nullable=False),
            sa.Column('is_success_fee_adjusted_against_listing_fee', sa.Boolean(), server_default='false', nullable=False),
            sa.Column('is_subscription_exempt', sa.Boolean(), server_default='false', nullable=False),
            sa.Column('is_listing_fee_exempt', sa.Boolean(), server_default='false', nullable=False),
            sa.Column('is_success_fee_exempt', sa.Boolean(), server_default='false', nullable=False),
            sa.Column('subscription_fee_exemption_reason', sa.Text(), nullable=True, comment='Reason for subscription fee exemption'),
            sa.Column('listing_fee_exemption_reason', sa.Text(), nullable=True, comment='Reason for listing fee exemption'),
            sa.Column('success_fee_exemption_reason', sa.Text(), nullable=True, comment='Reason for success fee exemption'),
            sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
            sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('created_by', sa.String(length=255), nullable=True),
            sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.Column('updated_by', sa.String(length=255), nullable=True),
            sa.CheckConstraint("organization_type IN ('Lender', 'Municipality', 'Admin', 'Govt', 'NIUA')", name='check_organization_type'),
            sa.CheckConstraint('listing_fee_percentage >= 0 AND listing_fee_percentage <= 100', name='check_listing_fee_percentage'),
            sa.CheckConstraint('success_fee_percentage >= 0 AND success_fee_percentage <= 100', name='check_success_fee_percentage'),
            sa.PrimaryKeyConstraint('id')
        )
        # Create indexes only if table was just created
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('perdix_mp_fee_configurations')]
        if 'ix_perdix_mp_fee_configurations_id' not in existing_indexes:
            op.create_index(op.f('ix_perdix_mp_fee_configurations_id'), 'perdix_mp_fee_configurations', ['id'], unique=False)
        if 'ix_perdix_mp_fee_configurations_organization_id' not in existing_indexes:
            op.create_index(op.f('ix_perdix_mp_fee_configurations_organization_id'), 'perdix_mp_fee_configurations', ['organization_id'], unique=True)
    
    # Create perdix_mp_menu_master if it doesn't exist
    if 'perdix_mp_menu_master' not in existing_tables:
        op.create_table('perdix_mp_menu_master',
            sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
            sa.Column('menu_name', sa.String(length=255), nullable=False),
            sa.Column('menu_icon', sa.String(length=255), nullable=True),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('display_order', sa.Integer(), nullable=True),
            sa.Column('status', sa.String(length=50), server_default='A', nullable=False),
            sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('created_by', sa.String(length=255), nullable=True),
            sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_by', sa.String(length=255), nullable=True),
            sa.CheckConstraint("status IN ('A', 'I')", name='check_menu_status'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('menu_name')
        )
        # Create index only if table was just created
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('perdix_mp_menu_master')]
        if 'ix_perdix_mp_menu_master_id' not in existing_indexes:
            op.create_index(op.f('ix_perdix_mp_menu_master_id'), 'perdix_mp_menu_master', ['id'], unique=False)
    
    # Create perdix_mp_submenu_master if it doesn't exist
    if 'perdix_mp_submenu_master' not in existing_tables:
        op.create_table('perdix_mp_submenu_master',
            sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
            sa.Column('submenu_name', sa.String(length=255), nullable=False),
            sa.Column('submenu_icon', sa.String(length=255), nullable=True),
            sa.Column('route', sa.String(length=500), nullable=False),
            sa.Column('menu_id', sa.BigInteger(), nullable=False),
            sa.Column('display_order', sa.Integer(), nullable=True),
            sa.Column('status', sa.String(length=50), server_default='A', nullable=False),
            sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('created_by', sa.String(length=255), nullable=True),
            sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_by', sa.String(length=255), nullable=True),
            sa.CheckConstraint("status IN ('A', 'I')", name='check_submenu_status'),
            sa.ForeignKeyConstraint(['menu_id'], ['perdix_mp_menu_master.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('submenu_name', name='uq_menu_submenu_name')
        )
        # Create indexes only if table was just created
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('perdix_mp_submenu_master')]
        if 'ix_perdix_mp_submenu_master_id' not in existing_indexes:
            op.create_index(op.f('ix_perdix_mp_submenu_master_id'), 'perdix_mp_submenu_master', ['id'], unique=False)
        if 'ix_perdix_mp_submenu_master_menu_id' not in existing_indexes:
            op.create_index(op.f('ix_perdix_mp_submenu_master_menu_id'), 'perdix_mp_submenu_master', ['menu_id'], unique=False)
    
    # Create perdix_mp_role_org_submenu_mapping if it doesn't exist
    if 'perdix_mp_role_org_submenu_mapping' not in existing_tables:
        op.create_table('perdix_mp_role_org_submenu_mapping',
            sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
            sa.Column('role_id', sa.BigInteger(), nullable=False),
            sa.Column('org_type', sa.String(length=50), nullable=False),
            sa.Column('submenu_id', sa.BigInteger(), nullable=False),
            sa.Column('status', sa.String(length=50), server_default='A', nullable=False),
            sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('created_by', sa.String(length=255), nullable=True),
            sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_by', sa.String(length=255), nullable=True),
            sa.CheckConstraint("org_type IN ('municipality', 'lender', 'munify', 'government')", name='check_org_type'),
            sa.CheckConstraint("status IN ('A', 'I')", name='check_mapping_status'),
            sa.ForeignKeyConstraint(['submenu_id'], ['perdix_mp_submenu_master.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('role_id', 'org_type', 'submenu_id', name='uq_role_org_submenu_mapping')
        )
        # Create indexes only if table was just created
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('perdix_mp_role_org_submenu_mapping')]
        if 'idx_role_org_type' not in existing_indexes:
            op.create_index('idx_role_org_type', 'perdix_mp_role_org_submenu_mapping', ['role_id', 'org_type'], unique=False)
        if 'ix_perdix_mp_role_org_submenu_mapping_id' not in existing_indexes:
            op.create_index(op.f('ix_perdix_mp_role_org_submenu_mapping_id'), 'perdix_mp_role_org_submenu_mapping', ['id'], unique=False)
        if 'ix_perdix_mp_role_org_submenu_mapping_org_type' not in existing_indexes:
            op.create_index(op.f('ix_perdix_mp_role_org_submenu_mapping_org_type'), 'perdix_mp_role_org_submenu_mapping', ['org_type'], unique=False)
        if 'ix_perdix_mp_role_org_submenu_mapping_role_id' not in existing_indexes:
            op.create_index(op.f('ix_perdix_mp_role_org_submenu_mapping_role_id'), 'perdix_mp_role_org_submenu_mapping', ['role_id'], unique=False)
        if 'ix_perdix_mp_role_org_submenu_mapping_submenu_id' not in existing_indexes:
            op.create_index(op.f('ix_perdix_mp_role_org_submenu_mapping_submenu_id'), 'perdix_mp_role_org_submenu_mapping', ['submenu_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_perdix_mp_role_org_submenu_mapping_submenu_id'), table_name='perdix_mp_role_org_submenu_mapping')
    op.drop_index(op.f('ix_perdix_mp_role_org_submenu_mapping_role_id'), table_name='perdix_mp_role_org_submenu_mapping')
    op.drop_index(op.f('ix_perdix_mp_role_org_submenu_mapping_org_type'), table_name='perdix_mp_role_org_submenu_mapping')
    op.drop_index(op.f('ix_perdix_mp_role_org_submenu_mapping_id'), table_name='perdix_mp_role_org_submenu_mapping')
    op.drop_index('idx_role_org_type', table_name='perdix_mp_role_org_submenu_mapping')
    op.drop_table('perdix_mp_role_org_submenu_mapping')
    op.drop_index(op.f('ix_perdix_mp_submenu_master_menu_id'), table_name='perdix_mp_submenu_master')
    op.drop_index(op.f('ix_perdix_mp_submenu_master_id'), table_name='perdix_mp_submenu_master')
    op.drop_table('perdix_mp_submenu_master')
    op.drop_index(op.f('ix_perdix_mp_menu_master_id'), table_name='perdix_mp_menu_master')
    op.drop_table('perdix_mp_menu_master')
    op.drop_index(op.f('ix_perdix_mp_fee_configurations_organization_id'), table_name='perdix_mp_fee_configurations')
    op.drop_index(op.f('ix_perdix_mp_fee_configurations_id'), table_name='perdix_mp_fee_configurations')
    op.drop_table('perdix_mp_fee_configurations')
    op.drop_index(op.f('ix_master_table_list_id'), table_name='master_table_list')
    op.drop_table('master_table_list')
    # ### end Alembic commands ###
